baseURL = 'https://lucasmei.github.io'
languageCode = 'en-ca'
title = 'Lucas Mei - Linguistics'
theme = 'xmin'

[params]
    footer="[github](https://github.com/lucasmei)"

[menu]
[[menu.main]]
    name="home"
    pageRef="/"
    weight=10
[[menu.main]]
    name="about me"
    pageRef="aboutme"
    weight=20
[[menu.main]]
    name="skills"
    pageRef="skills"
    weight=30

[[menu.footer_1]]
    name="github"
    url="https://github.com/lucasmei"
    weight=0
[[menu.footer_2]]
    name="resume"
    url="TBA"
    weight=1
